changes to linaro gcc

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,8 +40,15 @@ jobs:
       - name: Install Linaro GCC 10.2
         run: |
           wget -q -c https://developer.arm.com/-/media/Files/downloads/gnu-a/${GCC_VERSION}/binrel/gcc-arm-${GCC_VERSION}-x86_64-arm-none-linux-gnueabihf.tar.xz
+          sudo mkdir -p /opt
           sudo tar xf gcc-arm-${GCC_VERSION}-x86_64-arm-none-linux-gnueabihf.tar.xz -C /opt
           rm gcc-arm-${GCC_VERSION}-x86_64-arm-none-linux-gnueabihf.tar.xz
+          export PATH=/opt/gcc-arm-${GCC_VERSION}-x86_64-arm-none-linux-gnueabihf/bin:$PATH
+          if [ ! -f /opt/gcc-arm-${GCC_VERSION}-x86_64-arm-none-linux-gnueabihf/bin/arm-none-linux-gnueabihf-gcc ]; then
+            echo "Error: Toolchain binary not found"
+            ls -la /opt/gcc-arm-${GCC_VERSION}-x86_64-arm-none-linux-gnueabihf/bin/
+            exit 1
+          fi
           arm-none-linux-gnueabihf-gcc --version
 
       - name: Setup ARM Library Symlinks
@@ -69,6 +76,18 @@ jobs:
           mv -v ./dao/cdrdao ./utils/toc2cue $STARTDIR/Scripts/.config/mister-cdrdao
           cd $STARTDIR
           rm -rf cdrdao-${CDRDAO_VERSION} cdrdao-${CDRDAO_VERSION}.tar.bz2
+
+      - name: Download Redump DAT Files
+        run: |
+          STARTDIR=$PWD
+          for target in PSX:psx Saturn:ss MegaCD:mcd TGFX16-CD:pce NeoGeo-CD:ngcd; do
+            system=$(echo $target | awk -F: '{print $1}')
+            url=$(echo $target | awk -F: '{print $2}')
+            echo "==> Downloading ${system} dat file..."
+            wget -q http://redump.org/datfile/${url}/ -O ${system}.zip
+            unzip -p ${system}.zip > $STARTDIR/Scripts/.config/mister-cdrdao/${system}.dat
+            rm ${system}.zip
+          done
 
       - name: Verify Build
         run: |
